[Variables]

skinSize=500
lastSetWidth=500

Player=AIMP
alignRight=0

activePlugin=NowPlaying

topTextWidth=226
bottomTextWidth=119

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=AIMP
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Kalam
thickFont=Impact
controlsFont=Comic Sans MS

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=92.5
hairlinePositionHor=107.5
topTextPositionHor=123.75
playCtrlPositionHor=50
settingsTextPositionHor=57.5
indicatorPositionHor=35
indicatorPositionHorPure=20
conflictIndicatorPositionHor=15
conflictIndicatorPositionHorPure=40
